spring.datasource.url=jdbc:postgresql://postgres-taskflow:5432/taskflow
spring.datasource.username=taskuser
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
